replicaCount: 3

image:
  repository: christianbalderrama/blue-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80
  targetPort: 3000
deployment:
  containerPort: 3000
  env:
    - name: PORT
      value: "3000"

resources: {}
# We can specify resource limits and requests here.

nodeSelector: {}

tolerations: []

affinity: {}