apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deployment
  namespace: default
  labels:
    app: test-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          # {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        # {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        # {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        # {{- toYaml .Values.tolerations | nindent 8 }}