apiVersion: v1
kind: Service
metadata:
  name: test-svc
  namespace: default
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: test-app